### ISSUE TITLE
InvalidType error when using Export-vCheckSettings

### ISSUE THREAD

**Issue by rkleijwegt** [alanrenouf/vCheck-vSphere#309]
Tried to use Export-vCheckSettings before upgrading to the 6.22 release 7dccdad6a19f57aa6e165c8f62c0f73772a66b2c using the [instructions on the vCheck-vSphere wiki](https://github.com/alanrenouf/vCheck-vSphere/wiki/Export-Import-Settings). Unfortunately I was presented with a bunch of InvalidType errors. It still worked last week when I upgraded from 6.20-alpha-1 to commit 617e20c582b33a3ba9acc2d6037ee6994fa40b67. The exact error message is as follows:
```
New-Object : Cannot find type [â?TypeName PSObject â?Prop]: make sure the assembly containing this type is loaded.
At E:\scripts\vCheck\vCheckUtils.ps1:366 char:32
+             $currentsetting = New-Object <<<<  â?"TypeName PSObject â?"Prop $settings
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
```
I decided to bite the bullet this time and run the config wizard from a clean 6.22 install and manually enter the configuration values. But it would be great to have this fixed in a future release.

**Comment by rkleijwegt** [comment]
This actually seems fixed in commit 3cd1e525046b023ac3777ecff72dbb98a735f058 by @othercwood. However when I download the release 6.22 zip file the relevant line 366 still shows:
```powershell
$currentsetting = New-Object â€“TypeName PSObject â€“Prop $settings
```
Any ideas as to why this is happening?

**Comment by rkleijwegt** [comment]
Just tried to download the zip file containing the latest commit b97d52054ea0cd2aa8273ef273acf8e62295582d.

Strangely this commit shows an update in vCheckUtils.ps1 on the relevant line without any noticable changes. I guess this was probably a character encoding issue?

Never mind this issue then. :confused:
